version: '3.8'

services:
  tabletap:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: tabletap-app-prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tabletap.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.tabletap.tls=true"
      - "traefik.http.routers.tabletap.tls.certresolver=letsencrypt"

